config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  get 'public_recipes', to: 'public_recipes#index'
  # post 'toggle_public', to: 'recipes#toggle', as: 'toggle_public'

  resources :users, only: [:index, :show] do
    resources :new_recipes, only: [:index, :show, :new, :create, :destroy]
  end

  resources :users do
    resources :new_recipes do
      resources :recipe_foods
    end
  end  
  

  resources :foods
  resources :recipe_foods, only: [:create, :destroy]

  resources :new_recipes do
    resources :recipe_foods, only: [:index, :create, :destroy]
  end

  resources :users do
    resources :recipes, controller: 'new_recipes' do
      resources :recipe_foods, only: [:destroy, :edit, :update]
    end
  end

  resources :users do
    resources :new_recipes do
      member do
    post 'make_public'
  end
      resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
    end
  end
end

app/views/shared/_navbar.html.erb
<header class="p-3 bg-success">
  <div class="container">
    <div class="flex items-center justify-between">
      <h3 class="text-white text-lg font-bold mt-2">Recipe App</h3>
      <ul class="flex space-x-4">
        <li class="nav-item">
          <%= link_to "Add New Foods", foods_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'List of Recipes', new_recipes_path, class: "nav-link text-white" %>
        </li>
        <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link text-white"
 %>

        <li class="nav-item">
          <%= link_to "Shopping List", shopping_list_path, class: "nav-link text-white" %>
        </li>
      </ul>
      <div class="flex items-center space-x-4">
        <% if user_signed_in? %>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-warning mt-2" %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-light me-2" %>
          <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</header>