config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  get 'public_recipes', to: 'public_recipes#index'
  # post 'toggle_public', to: 'recipes#toggle', as: 'toggle_public'

  resources :users, only: [:index, :show] do
    resources :new_recipes, only: [:index, :show, :new, :create, :destroy]
  end

  resources :users do
    resources :new_recipes do
      resources :recipe_foods
    end
  end  
  

  resources :foods
  resources :recipe_foods, only: [:create, :destroy]

  resources :new_recipes do
    resources :recipe_foods, only: [:index, :create, :destroy]
  end

  resources :users do
    resources :recipes, controller: 'new_recipes' do
      resources :recipe_foods, only: [:destroy, :edit, :update]
    end
  end

  resources :users do
    resources :new_recipes do
      member do
    post 'make_public'
  end
      resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_header.html.erb
<nav>
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to 'Add New Recipe', new_new_recipe_path %></li>
      <li><%= link_to 'Add New Food', new_food_path %></li>
      <li><%= link_to 'List of Recipes', new_recipes_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>
</header>

app/views/welcome/index.html.erb
<div class="welcome-content">
  <h1>Welcome to the Recipe App</h1>
  <p>Explore delicious recipes and create your own culinary masterpieces.</p>
</div>