config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  get 'public_recipes', to: 'public_recipes#index'
  # post 'toggle_public', to: 'recipes#toggle', as: 'toggle_public'

  resources :users, only: [:index, :show] do
    resources :new_recipes, only: [:index, :show, :new, :create, :destroy]
  end

  resources :users do
    resources :new_recipes do
      resources :recipe_foods
    end
  end  
  

  resources :foods
  resources :recipe_foods, only: [:create, :destroy]

  resources :new_recipes do
    resources :recipe_foods, only: [:index, :create, :destroy]
  end

  resources :users do
    resources :recipes, controller: 'new_recipes' do
      resources :recipe_foods, only: [:destroy, :edit, :update]
    end
  end

  resources :users do
    resources :new_recipes do
      member do
    post 'make_public'
  end
      resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
    end
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'NewRecipe'
  belongs_to :new_recipe
  belongs_to :food

  def food_name
    food&.name
  end

  def total_price
    quantity * food.price
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    @recipe = NewRecipe.find(params[:recipe_food][:new_recipe_id])

    @recipe_foods = RecipeFood.new(recipe_foods_params)
    @recipe_foods.recipe = @recipe

    respond_to do |format|
      format.html do
        if @recipe_foods.save
          redirect_to user_new_recipe_path(current_user, @recipe), notice: 'Ingredient saved successfully'
        else
          redirect_to user_recipe_path(current_user, @recipe.id), alert: 'Error, Ingredient not created!'
        end
      end
    end
  end

  def new
    @recipe = NewRecipe.find(params[:new_recipe_id])
    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe = NewRecipe.find(params[:recipe_id]) # Change here
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe = NewRecipe.find(params[:new_recipe_id])
    @recipe_food = RecipeFood.find(params[:id])

    respond_to do |format|
      if @recipe_food.update(recipe_foods_params)
        format.html do
          redirect_to user_new_recipe_path(current_user, @recipe), notice: 'Ingredient updated successfully'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @recipe = NewRecipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.includes(:recipe, :food).find(params[:id])
    @recipe_food.delete

    respond_to do |format|
      format.html do
        redirect_to user_recipe_path(current_user, @recipe.id), notice: 'Ingredient deleted successfully'
      end
    end
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity, :new_recipe_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<div class="container mt-4">
  <div class="card p-4 mb-4 shadow">
    <h3 class="mb-4 text-xl font-medium text-gray-900">Modify Ingredient</h3>
    <%= form_for(@recipe_food, url: user_new_recipe_recipe_food_path(current_user, @recipe, @recipe_food), method: :patch) do |f| %>
      <div class="mb-3">
        <%= f.label :food_id, "Food", class: "form-label" %>
        <%= f.select :food_id, current_user.foods.map { |food| [food.name, food.id] }, {}, class: "form-select" %>
      </div>
      <div class="mb-3">
        <%= f.label :quantity, "Quantity", class: "form-label" %>
        <%= f.number_field :quantity, class: "form-control" %>
      </div>
      <div class="text-center">
        <%= f.submit "Update ingredient", class: "btn btn-success w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container mt-4">
  <div class="card p-4 mb-4 shadow">
    <h3 class="mb-4 text-xl font-medium text-gray-900">Add Ingredient</h3>
    <%= form_with model: RecipeFood, data: { turbo: false }, url: user_new_recipe_recipe_foods_path(current_user, @recipe), class: "row g-3" do |f| %>
      <%= f.hidden_field :new_recipe_id, value: @recipe.id %>
        <div class="mb-3">
        <%= f.label :food_id, "Food", class: "form-label" %>
        <%= f.select :food_id, current_user.foods.map { |food| [food.name, food.id] }, {}, class: "form-select" %>
      </div>
      <div class="mb-3">
      <%= f.label :quantity, "Quantity", class: "form-label ms-3" %>
      <%= f.number_field :quantity, class: "form-control mb-3" %>
      </div>
      <div class="text-center">
      <%= f.submit "Add ingredient", class: "btn btn-success w-100 mb-2" %>
      </div>
    <% end %>
  </div>
</div>