config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  get 'public_recipes', to: 'public_recipes#index'
  # post 'toggle_public', to: 'recipes#toggle', as: 'toggle_public'

  resources :users, only: [:index, :show] do
    resources :new_recipes, only: [:index, :show, :new, :create, :destroy]
  end

  resources :users do
    resources :new_recipes do
      resources :recipe_foods
    end
  end  
  

  resources :foods
  resources :recipe_foods, only: [:create, :destroy]

  resources :new_recipes do
    resources :recipe_foods, only: [:index, :create, :destroy]
  end

  resources :users do
    resources :recipes, controller: 'new_recipes' do
      resources :recipe_foods, only: [:destroy, :edit, :update]
    end
  end

  resources :users do
    resources :new_recipes do
      member do
    post 'make_public'
  end
      resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
    end
  end
end

app/models/new_recipe.rb
class NewRecipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/new_recipes_controller.rb
class NewRecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = NewRecipe.where(user_id: current_user.id)
  end

  def new
    @recipe = NewRecipe.new
  end

  def show
    @recipe = NewRecipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods # Load associated recipe_foods
  end

  def create
    @recipe = current_user.new_recipes.new(recipe_params)

    if @recipe.save
      redirect_to new_recipes_path, notice: 'The recipe was successfully created.'
    else
      render :new, alert: 'The recipe was not created.'
    end
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'The recipe was successfully updated.'
    else
      render :edit, alert: 'The recipe was not updated.'
    end
  end

  def make_public
    @recipe = NewRecipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    render json: { public: @recipe.public }
    head :no_content
  end

  def destroy
    @recipe = NewRecipe.find(params[:id])
    @recipe.destroy
    redirect_to user_new_recipes_path(current_user), notice: 'The recipe was successfully deleted.'
  end

  private

  def set_recipe
    @recipe = NewRecipe.find(params[:id])
  end

  def recipe_params
    params.require(:new_recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/new_recipes_helper.rb
module NewRecipesHelper
end

app/views/new_recipes/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <%= link_to "Create new Recipe", new_user_new_recipe_path(current_user), class: "btn btn-success mb-4" %> 
      
      <% @recipes.each do |recipe| %>
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-md-8">
              <h5 class="card-title">
                <%= link_to recipe.name, user_new_recipe_path(current_user, recipe), class: "text-primary" %>
              </h5>
              <%= button_to user_new_recipe_path(current_user, recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-2" do %>
                Remove
              <% end %>
            </div>
            <div class="col-md-4 text-center">
              
              <p class="card-text text-success"><%= recipe.description %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/new_recipes/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <h2 class="text-center mb-4">Add New Recipe</h2>
      <%= form_with model: @recipe, url: user_new_recipes_path(current_user), method: :post do |f|  %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_field :description, autofocus: true, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :preparation_time, class: "form-label" %>
          <%= f.number_field :preparation_time, step: 0.1, autofocus: true, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :cooking_time, class: "form-label" %>
          <%= f.number_field :cooking_time, step: 0.1, autofocus: true, class: "form-control" %>
        </div>
        <div class="mb-3 form-check">
          <%= f.check_box :public, class: "form-check-input" %>
          <%= f.label :public, class: "form-check-label" %>
        </div>
        <div class="d-flex justify-content-between">
          <%= f.submit "Save", class: "btn btn-primary" %>
          <%= link_to 'Back', url_for(:back), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
  <% if flash[:notice] %>
    <div class="alert alert-success mt-3"><%= flash[:notice] %></div>
  <% end %>
</div>

app/views/new_recipes/show.html.erb
<div class="container">
      <div class="block rounded-lg shadow-lg bg-white p-6 mb-3 mt-2">
        <div class="mb-6 text-center mt-3">
          <strong>Recipe Name: </strong><%= @recipe.name  %>
        </div>
        <div class="flex ms-5 mt-3 mb-6">
        <div class="mr-5">
          <strong>Public:</strong>
        </div>
        <div class="form-check form-switch me-5">
          <% if can? :manage, @recipe %>
          <%= button_to make_public_user_new_recipe_path(user_id: @recipe.user_id, id: @recipe.id), method: :post, data: { turbo: false }, class: "toggle-button" do %>
            <% if @recipe.public %>
              <input type="checkbox" id="toggle-example-checked" class="form-check-input" checked>
            <% else %>
              <input type="checkbox" id="toggle-example-checked" class="form-check-input">
            <% end %>
          <% end %>
            <% end %>
        </div>
      </div>
        <div class="mb-6 ms-5">Preparation time: <%= @recipe.preparation_time %> hours</div>
        <div class="mb-6 ms-5">Cooking time: <%= @recipe.cooking_time %> hours</div>
        <div class="mb-6 ms-5">Steps go here...</div>
        <div class="flex flex-row mb-6">
        <div class="flex gap-6 ms-5">
          <% if @recipe.user_id == current_user.id %>
            <div class="flex-container my-5 pb-4">
              <%= link_to 'Generate shopping list', shopping_list_path, class: "btn btn-info" %>
              <% if current_user.id == @recipe.user_id %>
              <%= link_to 'Add Ingredient', new_user_new_recipe_recipe_food_path(current_user, @recipe), class: "btn btn-info" %>
            <% end %>
            
            </div>
          <% end %>
        </div>
      </div>
      </div>      
      <div class="container">
      <div class="block rounded-lg shadow-lg bg-white p-6 mb-3 mt-2">
        <table class="table table-bordered">
          <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-center">Food</th>
              <th class="py-3 px-6 text-center">Quantity</th>
              <th class="py-3 px-6 text-center">Value</th>
              <th class="py-3 px-6 text-center">Action</th>
            </tr>
          </thead>
          <tbody class="text-gray-600 text-sm font-light">
            <% @recipe.recipe_foods.each do |recipe| %>
              <tr class="border-b border-gray-200 hover:bg-gray-100">
                <td class="py-3 px-6 text-left whitespace-nowrap">
                  <div class="flex items-center">
                    <%= recipe.food.name %>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <%= recipe.quantity %>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <%= number_to_currency recipe.quantity * recipe.food.price %>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                <div class="flex items-center justify-center">
                  <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                    <% if current_user.id == recipe.recipe.user_id %>
                      <div class="flex gap-3">
                        <%= button_to user_recipe_recipe_food_path(current_user, @recipe, recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                          Remove
                        <% end %>
                        <%= link_to edit_user_recipe_recipe_food_path(current_user, @recipe, recipe), class: "btn btn-success" do %>
                          Modify
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>